"""Event management page for logical, catalog-only grouping."""
from __future__ import annotations

from PySide6.QtWidgets import QComboBox, QFormLayout, QLabel, QLineEdit, QPushButton, QTableWidget


def build_events_page(owner: object, layout: object, tables: dict[str, QTableWidget]) -> None:
    intro = QLabel("Events group media logically. Creating an event never moves or rewrites original files.")
    intro.setWordWrap(True)
    layout.addWidget(intro)
    form = QFormLayout()
    owner.event_name = QLineEdit()
    owner.event_name.setPlaceholderText("e.g. Edinburgh trip")
    owner.event_start = QLineEdit()
    owner.event_start.setPlaceholderText("YYYY-MM-DD (optional)")
    owner.event_end = QLineEdit()
    owner.event_end.setPlaceholderText("YYYY-MM-DD (optional)")
    owner.event_type = QComboBox()
    owner.event_type.addItem("Other", "other")
    for value, label in (("trip", "Trip"), ("holiday", "Holiday"), ("family", "Family"), ("school", "School"), ("music", "Music"), ("work", "Work"), ("celebration", "Celebration")):
        owner.event_type.addItem(label, value)
    owner.event_default_place = QComboBox()
    owner.event_default_place.addItem("No default place", None)
    form.addRow("Event name", owner.event_name)
    form.addRow("Start date", owner.event_start)
    form.addRow("End date", owner.event_end)
    form.addRow("Type", owner.event_type)
    form.addRow("Default place", owner.event_default_place)
    layout.addLayout(form)
    create = QPushButton("Create event")
    create.clicked.connect(owner._create_event)
    layout.addWidget(create)
    update = QPushButton("Update selected event")
    update.clicked.connect(owner._update_event)
    layout.addWidget(update)
    delete = QPushButton("Delete selected event")
    delete.clicked.connect(owner._delete_event)
    layout.addWidget(delete)
    refresh = QPushButton("Refresh events")
    refresh.clicked.connect(owner._refresh_events)
    layout.addWidget(refresh)
    detail = QPushButton("Open selected event detail")
    detail.clicked.connect(owner._open_selected_event_detail)
    layout.addWidget(detail)
    suggest = QPushButton("Suggest events from capture dates")
    suggest.setToolTip("Create low-confidence, catalog-only suggestions; existing manual events are preserved.")
    suggest.clicked.connect(owner._suggest_events)
    layout.addWidget(suggest)
    approve = QPushButton("Accept selected suggestion")
    approve.setToolTip("Promote a suggested Event to a normal Event without changing any media.")
    approve.clicked.connect(owner._approve_event_suggestion)
    layout.addWidget(approve)
    dismiss = QPushButton("Dismiss selected suggestion")
    dismiss.setToolTip("Remove the suggestion and remember the date range so it is not recreated automatically.")
    dismiss.clicked.connect(owner._dismiss_event_suggestion)
    layout.addWidget(dismiss)
    owner.event_range_hint = QLabel("When both dates are supplied, Create event also adds catalogued media in that inclusive range.")
    owner.event_range_hint.setWordWrap(True)
    layout.addWidget(owner.event_range_hint)
    owner.events_result = QLabel("Events are catalog metadata.")
    owner.events_result.setWordWrap(True)
    layout.addWidget(owner.events_result)
    table = QTableWidget()
    table.cellClicked.connect(owner._load_event_row)
    table.cellDoubleClicked.connect(owner._open_event_row)
    tables["Events"] = table
    layout.addWidget(table)
