"""Settings landing page construction."""
from __future__ import annotations

from PySide6.QtWidgets import QComboBox, QFormLayout, QHBoxLayout, QLabel, QLineEdit, QProgressBar, QPushButton, QSpinBox


def build_settings_page(owner: object, layout: object) -> None:
    intro = QLabel(
        "PhotoVault keeps backup truth separate from photo enrichment. Use the links below to reach catalog, backup, and intelligence controls."
    )
    intro.setObjectName("StatusSummary")
    intro.setWordWrap(True)
    layout.addWidget(intro)
    sections = (
        ("Library and privacy", "Photos remain local; thumbnails and enrichment are rebuildable catalog data."),
        ("Backup defaults", "Verified copies, atomic destination writes, and stable drive identity remain the safety defaults."),
        ("AI & Intelligence", "Category, people, place, and duplicate analysis are optional and never modify originals."),
    )
    for heading, description in sections:
        card = QLabel(f"{heading}\n{description}")
        card.setWordWrap(True)
        card.setObjectName("SettingsCard")
        layout.addWidget(card)
    ai_heading = QLabel("AI & Intelligence")
    ai_heading.setObjectName("SectionHeading")
    layout.addWidget(ai_heading)
    ai_help = QLabel(
        "Optional local analysis runs in a background worker. Model output is advisory and remains separate from user Tags."
    )
    ai_help.setWordWrap(True)
    layout.addWidget(ai_help)
    ai_form = QFormLayout()
    owner.category_model_path = QLineEdit()
    owner.category_model_path.setPlaceholderText("Path to local ONNX model (stored outside Git)")
    owner.category_labels_path = QLineEdit()
    owner.category_labels_path.setPlaceholderText("Path to matching labels.txt")
    owner.category_limit = QSpinBox()
    owner.category_limit.setRange(0, 10_000_000)
    owner.category_limit.setSpecialValueText("All images")
    owner.category_top_k = QSpinBox()
    owner.category_top_k.setRange(1, 100)
    owner.category_top_k.setValue(5)
    ai_form.addRow("Category model", owner.category_model_path)
    ai_form.addRow("Category labels", owner.category_labels_path)
    ai_form.addRow("Analysis limit", owner.category_limit)
    ai_form.addRow("Top labels", owner.category_top_k)
    layout.addLayout(ai_form)
    ai_actions = QHBoxLayout()
    owner.category_start_button = QPushButton("Run category analysis")
    owner.category_start_button.clicked.connect(owner._start_category_analysis)
    ai_actions.addWidget(owner.category_start_button)
    owner.category_cancel_button = QPushButton("Cancel analysis")
    owner.category_cancel_button.setEnabled(False)
    owner.category_cancel_button.clicked.connect(owner._cancel_category_analysis)
    ai_actions.addWidget(owner.category_cancel_button)
    open_categories = QPushButton("Open Categories")
    open_categories.clicked.connect(lambda: owner._select_page("Categories"))
    ai_actions.addWidget(open_categories)
    layout.addLayout(ai_actions)
    owner.category_progress = QProgressBar()
    owner.category_progress.setRange(0, 100)
    owner.category_progress.setValue(0)
    owner.category_progress.setFormat("Ready")
    layout.addWidget(owner.category_progress)
    duplicate_heading = QLabel("Visual duplicate analysis")
    duplicate_heading.setObjectName("SubsectionHeading")
    layout.addWidget(duplicate_heading)
    duplicate_help = QLabel(
        "Similarity groups are advisory only. Exact SHA-256 and backup protection remain separate safety decisions."
    )
    duplicate_help.setWordWrap(True)
    layout.addWidget(duplicate_help)
    duplicate_form = QFormLayout()
    owner.duplicate_algorithm = QComboBox()
    owner.duplicate_algorithm.addItem("Perceptual hash (pHash)", "phash64")
    owner.duplicate_algorithm.addItem("Difference hash (dHash)", "dhash64")
    owner.duplicate_threshold = QSpinBox()
    owner.duplicate_threshold.setRange(0, 64)
    owner.duplicate_threshold.setValue(8)
    duplicate_form.addRow("Similarity method", owner.duplicate_algorithm)
    duplicate_form.addRow("Similarity threshold", owner.duplicate_threshold)
    layout.addLayout(duplicate_form)
    duplicate_actions = QHBoxLayout()
    run_duplicates = QPushButton("Find advisory groups")
    run_duplicates.clicked.connect(lambda: owner._visual_duplicates(owner.duplicate_algorithm, owner.duplicate_threshold))
    duplicate_actions.addWidget(run_duplicates)
    open_duplicates = QPushButton("Open Visual Duplicates")
    open_duplicates.clicked.connect(lambda: owner._select_page("Visual Duplicates"))
    duplicate_actions.addWidget(open_duplicates)
    layout.addLayout(duplicate_actions)
    places_heading = QLabel("Places")
    places_heading.setObjectName("SubsectionHeading")
    layout.addWidget(places_heading)
    places_help = QLabel("Embedded GPS is preserved. Clustering is read-only derived metadata; manually assigned places remain separate and take precedence in the Library.")
    places_help.setWordWrap(True)
    layout.addWidget(places_help)
    places_form = QFormLayout()
    owner.place_cluster_radius = QSpinBox()
    owner.place_cluster_radius.setRange(1, 100_000)
    owner.place_cluster_radius.setValue(100)
    owner.place_cluster_radius.setSuffix(" m")
    places_form.addRow("GPS cluster radius", owner.place_cluster_radius)
    layout.addLayout(places_form)
    open_places = QPushButton("Open Places")
    open_places.clicked.connect(lambda: owner._select_page("Places"))
    layout.addWidget(open_places)
    people_heading = QLabel("People and face analysis")
    people_heading.setObjectName("SubsectionHeading")
    layout.addWidget(people_heading)
    people_help = QLabel("Manual People assignments are always available. The optional macOS Vision import reads derived JSON only and never edits original media.")
    people_help.setWordWrap(True)
    layout.addWidget(people_help)
    owner.people_features_json = QLineEdit()
    owner.people_features_json.setPlaceholderText("Path to macOS Vision features JSON")
    layout.addWidget(owner.people_features_json)
    people_actions = QHBoxLayout()
    import_people = QPushButton("Import Vision people groups")
    import_people.clicked.connect(owner._import_people_features)
    people_actions.addWidget(import_people)
    open_people = QPushButton("Open People")
    open_people.clicked.connect(lambda: owner._select_page("People"))
    people_actions.addWidget(open_people)
    layout.addLayout(people_actions)
    for button_text, target in (("Open Advanced Tools", "Advanced Tools"), ("Open Catalog Recovery", "Catalog Recovery")):
        button = QPushButton(button_text)
        button.clicked.connect(lambda _checked=False, page=target: owner._select_page(page))
        layout.addWidget(button)
